name: waiting_list_sms_notifier
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.7
  http: ^1.5.0
  intl: ^0.20.2
  pocketbase: ^0.23.0+1
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
